import supabase from './db-client.js';
import { getAuthUser, unauthorized } from './auth.js';

function buildMarkdown(scan, findings) {
  const L = [];
  L.push('# Adversarial QA Report — ' + scan.name);
  L.push('');
  L.push('> Generated by RedTeam QA · Autonomous Adversarial QA Engine · Zero-hallucination policy');
  L.push('');
  L.push('| Field | Value |');
  L.push('|---|---|');
  L.push('| Run ID | #' + String(scan.id).padStart(4, '0') + ' |');
  L.push('| Target | ' + scan.target_url + ' |');
  L.push('| Spec | ' + scan.spec_type + ' |');
  L.push('| Environment | ' + scan.environment + ' |');
  L.push('| Started | ' + scan.started_at + ' |');
  L.push('| Completed | ' + (scan.completed_at || 'in progress') + ' |');
  L.push('| Requests sent | ' + scan.requests_sent + ' |');
  L.push('| Active modules | ' + (scan.modules || []).join(', ') + ' |');
  L.push('');
  L.push('## Executive Summary');
  L.push('');
  L.push(
    'The adversarial engine executed ' +
      scan.requests_sent +
      ' requests across ' +
      (scan.modules || []).length +
      ' attack batteries. ' +
      findings.length +
      ' findings were confirmed with captured request/response evidence.'
  );
  L.push('');
  L.push('| Severity | Count |');
  L.push('|---|---|');
  L.push('| Critical | ' + scan.critical_count + ' |');
  L.push('| High | ' + scan.high_count + ' |');
  L.push('| Medium | ' + scan.medium_count + ' |');
  L.push('| Low | ' + scan.low_count + ' |');
  L.push('');
  L.push('## CI/CD Gate Verdict');
  L.push('');
  if (scan.gate_status === 'pass') {
    L.push('**PASS** — no Critical or High severity findings. Safe to promote to the next environment.');
  } else if (scan.gate_status === 'fail') {
    L.push(
      '**FAIL** — ' +
        scan.critical_count +
        ' Critical and ' +
        scan.high_count +
        ' High severity findings. Pipeline policy blocks promotion until remediated.'
    );
  } else {
    L.push('Pending — scan still in progress.');
  }
  L.push('');
  L.push('## Findings (' + findings.length + ')');
  findings.forEach((f, i) => {
    L.push('');
    L.push('### ' + (i + 1) + '. [' + String(f.severity).toUpperCase() + '] ' + f.title);
    L.push('');
    L.push('- **Categorization:** ' + f.cwe + ' · OWASP ' + f.owasp + ' · ' + f.category);
    L.push('- **Severity:** ' + String(f.severity).toUpperCase() + ' (CVSS v3.1: ' + Number(f.cvss).toFixed(1) + ')');
    L.push('- **Status:** ' + f.status);
    L.push('- **Endpoint:** ' + f.method + ' ' + f.endpoint);
    L.push('');
    L.push('**Reproduction (cURL):**');
    L.push('');
    L.push('```bash');
    L.push(f.curl);
    L.push('```');
    L.push('');
    L.push('**Expected response:** ' + f.expected_response);
    L.push('');
    L.push('**Actual response:** ' + f.actual_response);
    L.push('');
    L.push('**Business impact:** ' + f.business_impact);
    L.push('');
    L.push('**Remediation:** ' + f.remediation);
    L.push('');
    L.push('**Evidence:** ' + f.evidence);
  });
  L.push('');
  L.push('---');
  L.push('');
  L.push('*Every finding in this report is backed by captured request/response evidence. Candidates that could not be re-verified were eliminated as false positives.*');
  return L.join('\n');
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

  const user = await getAuthUser(req);
  if (!user) return unauthorized(res);

  try {
    const scanId = Number(req.query.scan_id);
    if (!scanId) return res.status(400).json({ error: 'scan_id is required' });
    const { data: scan, error } = await supabase.from('scans').select('*').eq('id', scanId).single();
    if (error || !scan) return res.status(404).json({ error: 'Scan not found' });
    const { data: findings, error: fErr } = await supabase
      .from('findings')
      .select('*')
      .eq('scan_id', scanId)
      .order('cvss', { ascending: false });
    if (fErr) throw fErr;
    return res.status(200).json({
      markdown: buildMarkdown(scan, findings || []),
      json: { scan, findings: findings || [] },
    });
  } catch (err) {
    console.error('report error:', err);
    res.status(500).json({ error: err.message });
  }
}
